project:
  type: website
  output-dir: docs

website:
  title: "hzg00-jpg"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - text: "Data Visualization"
        menu: 
          - text: "Food and beverages"
            href: food_beverages_tt.qmd
          - text: "Penguins"
            href: penguins.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



